apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: sinedon/edge-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: CONTENT_SERVICE_URL
              value: http://content-manager

            - name: PROGRESS_SERVICE_URL
              value: http://progress-manager

            - name: KEYCLOAK_CLIENT_SECRET
              value: edge-secret-dev-123

            - name: KEYCLOAK_ISSUER_URI
              value: http://localhost:8080/realms/picture-dictionary
---
apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  type: ClusterIP
  selector:
    app: edge-service
  ports:
    - port: 80
      targetPort: 8080